/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexduplicateRouteImport } from './routes/indexduplicate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReturnPolicyRouteImport } from './routes/return-policy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexduplicateRoute = IndexduplicateRouteImport.update({
  id: '/indexduplicate',
  path: '/indexduplicate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnPolicyRoute = ReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/indexduplicate': typeof IndexduplicateRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/indexduplicate': typeof IndexduplicateRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/indexduplicate': typeof IndexduplicateRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/indexduplicate'
    | '/login'
    | '/orders'
    | '/privacy'
    | '/reset-password'
    | '/return-policy'
    | '/search'
    | '/shipping-policy'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/category/$slug'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/indexduplicate'
    | '/login'
    | '/orders'
    | '/privacy'
    | '/reset-password'
    | '/return-policy'
    | '/search'
    | '/shipping-policy'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/category/$slug'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/indexduplicate'
    | '/login'
    | '/orders'
    | '/privacy'
    | '/reset-password'
    | '/return-policy'
    | '/search'
    | '/shipping-policy'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/category/$slug'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IndexduplicateRoute: typeof IndexduplicateRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReturnPolicyRoute: typeof ReturnPolicyRoute
  SearchRoute: typeof SearchRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexduplicate': {
      id: '/indexduplicate'
      path: '/indexduplicate'
      fullPath: '/indexduplicate'
      preLoaderRoute: typeof IndexduplicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-policy': {
      id: '/return-policy'
      path: '/return-policy'
      fullPath: '/return-policy'
      preLoaderRoute: typeof ReturnPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IndexduplicateRoute: IndexduplicateRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReturnPolicyRoute: ReturnPolicyRoute,
  SearchRoute: SearchRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
